#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
#      settings:
#        web-allow-others: true
#  datasource:
#    url: jdbc:h2:mem:test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update    # 스키마 자동 생성
#    show-sql: false        # SQL 쿼리 출력
#    properties:
#      hibernate:
#        format_sql: true  # SQL pretty print
#        jdbc:
#          time_zone: Asia/Seoul   # 서버 시간 서울로 변경